appdaemon:
  plugins:
    HASS:
      type: hass
    MQTT:
      type: mqtt
      namespace: mqtt # This is important
      client_host: core-mosquitto
      client_user: !secret mqtt_username
      client_password: !secret mqtt_password
  latitude: !secret lat
  longitude: !secret lon
  elevation: 32
  time_zone: Europe/Helsinki
http:
  url: http://127.0.0.1:5050
hadashboard:
admin:
api: