- id: palju_on
  alias: Palju päälle
  trigger:
  - platform: time
    at: "12:01:00"
  condition:
  - condition: state
    entity_id: input_select.housestatus
    state: "Päivä"
  action:
  - service: switch.turn_on
    entity_id: switch.suodatin
  - service: switch.turn_on
    entity_id: switch.lammitin
- id: palju_off
  alias: Palju pois
  trigger:
  - platform: time
    at: "20:00:00"
  action:
  - service: switch.turn_off
    entity_id: switch.suodatin
  - service: switch.turn_off
    entity_id: switch.lammitin
- id: palju_on_away
  alias: Palju päälle lomalla
  trigger:
  - platform: time
    at: "19:01:00"
  condition:
  - condition: state
    entity_id: input_select.housestatus
    state: "Pitkään poissa"
  action:
  - service: switch.turn_on
    entity_id: switch.suodatin