- id: ocatavia_heating_on
  alias: Octavia lämmitys
  trigger:
  - platform: state
    entity_id: binary_sensor.octavia_0b
    to: 'on'
  - platform: state
    entity_id: binary_sensor.octavia_10b
    to: 'on'
  - platform: state
    entity_id: binary_sensor.octavia_20b
    to: 'on'
  - platform: state
    entity_id: switch.octavia
    to: 'on'
  condition:
    condition: or
    conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: switch.octavia
        state: 'on'
      - condition: state
        entity_id: timer.octavia
        state: idle
    - condition: and
      conditions:
      - condition: state
        entity_id: binary_sensor.octavia_0b
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.autotalli_temperature
        below: 10
      - condition: state
        entity_id: input_boolean.octavia
        state: 'on'
    - condition: and
      conditions:
      - condition: state
        entity_id: binary_sensor.octavia_10b
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.autotalli_temperature
        below: -10
      - condition: state
        entity_id: input_boolean.octavia
        state: 'on'
    - condition: and
      conditions:
      - condition: state
        entity_id: binary_sensor.octavia_20b
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.autotalli_temperature
        below: -20
      - condition: state
        entity_id: input_boolean.octavia
        state: 'on'
  action:
  - service: script.turn_on
    entity_id: script.autojen_lammitys
    data:
      variables:
        car: timer.octavia
  - service: switch.turn_on
    entity_id: switch.octavia
  - service: telegram_bot.send_message
    data_template:
      title: '*Octavia lämmitys päälle*'
      target: !secret telegram_chat3
      message: 'Pyydetty lämmitysaika:  {% if is_state(''input_boolean.octavia'',
        ''on'')  -%}{{ states(''input_datetime.octavia'') }} {%- else -%}Käynnistetty
        käsin{%- endif %} autotallin lämpötila on {{ states(''sensor.autotalli_temperature'')
        }}'
  - service: input_boolean.turn_off
    entity_id: input_boolean.octavia
- id: ocatavia_heating_off
  alias: Octavia lämmitys pois
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.octavia
  action:
  - service: switch.turn_off
    entity_id: switch.octavia
  - service: telegram_bot.send_message
    data_template:
      title: '*Octavia lämmitys pois*'
      target: !secret telegram_chat3
      message: 'Pyydetty lämmitysaika oli:  {{ states(''input_datetime.octavia'')
        }} autotallin lämpötila on {{ states(''sensor.autotalli_temperature'') }}'
- id: garage_doors_check
  alias: Tarkista autotallin ovet
  trigger:
    platform: time
    at: '21:00'
  condition:
    condition: template
    value_template: '{{ states | selectattr(''entity_id'', ''in'', state_attr(''group.autotallinovet'',''entity_id''))
      | selectattr(''state'',''in'',[''on'',''open'']) | list | length >= 1 }}'
  action:
  - service: telegram_bot.send_message
    data_template:
      title: '*Autotallin ovet on auki*'
      target: !secret telegram_chat3
      message: '{% set open_doors = states | selectattr(''entity_id'', ''in'', state_attr(''group.autotallinovet'',''entity_id''))
        | selectattr(''state'',''in'',[''on'',''open'']) | map(attribute=''name'')
        | list %} {% if open_doors | length == 1 %} {{ open_doors[0] }} on auki. {%
        else %} {{ open_doors[:-1] | join('', '') }}{{'''' if open_doors | length
        > 2 else '' ''}} ja {{ open_doors[-1]}} on auki. {% endif %}'
- id: Garage_door_closed
  alias: Autotallin ovi kiinni
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/KytkinEteinen/action"
    payload: arrow_right_click
  condition:
  - condition: state
    entity_id: cover.autotallin_ovi
    state: open
  - condition: state
    entity_id: timer.garagedooropen
    state: idle
  action:
  - service: cover.close_cover
    entity_id: cover.autotallin_ovi
- id: Garage_door_timer
  alias: Autotallin ovi ajastin
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/KytkinEteinen/action"
    payload: arrow_right_click
  condition:
  - condition: state
    entity_id: cover.autotallin_ovi
    state: closed
  action:
  - service: timer.start
    data:    
      entity_id: timer.garagedooropen
      duration: '0:05:00'
- id: Garage_door_open
  alias: Autotallin ovi auki
  trigger:
    platform: state
    entity_id: binary_sensor.etuovianturi_contact
    to: 'on'
  condition:
  - condition: state
    entity_id: timer.garagedooropen
    state: active
  - condition: state
    entity_id: cover.autotallin_ovi
    state: closed
  action:
  - service: cover.open_cover
    entity_id: cover.autotallin_ovi
  - service: timer.cancel
    target:
      entity_id: timer.garagedooropen
- id: Overcurrent
  alias: Liikaa virtaa
  trigger:
  - platform: numeric_state
    entity_id: sensor.shellyem3_bcff4dfd1132_channel_a_current
    above: 25
  - platform: numeric_state
    entity_id: sensor.shellyem3_bcff4dfd1132_channel_b_current
    above: 25
  - platform: numeric_state
    entity_id: sensor.shellyem3_bcff4dfd1132_channel_c_current
    above: 25
  action:
  - service: number.set_value
    data:
      value: 12
    target:
      entity_id: number.go_echarger_202759_amp
- id: Freecurrent
  alias: Vapaata virtaa
  trigger:
  - platform: numeric_state
    entity_id: sensor.shellyem3_bcff4dfd1132_channel_a_current
    below: 18
    for:
      minutes: 10
  - platform: numeric_state
    entity_id: sensor.shellyem3_bcff4dfd1132_channel_b_current
    below: 18
    for:
      minutes: 10
  - platform: numeric_state
    entity_id: sensor.shellyem3_bcff4dfd1132_channel_c_current
    below: 18
    for:
      minutes: 10
  condition:
  - condition: numeric_state
    entity_id: sensor.shellyem3_bcff4dfd1132_channel_a_current
    below: 18
  - condition: numeric_state
    entity_id: sensor.shellyem3_bcff4dfd1132_channel_b_current
    below: 18
  - condition: numeric_state
    entity_id: sensor.shellyem3_bcff4dfd1132_channel_c_current
    below: 18
  action:
  - service: number.set_value
    data:
      value: 16
    target:
      entity_id: number.go_echarger_202759_amp
- id: Blockcarcharge
  alias: Auton lataus estetyksi
  trigger:
  - platform: state
    entity_id: sensor.go_echarger_202759_car
    to: "Idle"
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.go_echarger_202759_acs
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.enyaqmanuaali
  - service: select.select_option
    data:
      option: Neutral
    target:
      entity_id: select.go_echarger_202759_frc
- id: Carparked
  alias: Auton lataus valmiiksi
  trigger:
  - platform: state
    entity_id: sensor.go_echarger_202759_car
    from: "Idle"
  action:
  - service: select.select_option
    data:
      option: Neutral
    target:
      entity_id: select.go_echarger_202759_frc
- id: Carcharge
  alias: Auton lataus
  trigger:
  - platform: state
    entity_id: input_boolean.enyaqmanuaali
    to: "on"
  - platform: state
    entity_id: select.go_echarger_202759_frc
    to: "Charge"
  condition:
  - condition: not
    alias: "Auton pitää olla paikalla"
    conditions:
    - condition: state
      entity_id: sensor.go_echarger_202759_car
      state: "Idle"
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.go_echarger_202759_acs
  - service: select.select_option
    data:
      option: Charge
    target:
      entity_id: select.go_echarger_202759_frc

- id: freememory
  trigger:
  - platform: numeric_state
    entity_id: sensor.memory_free
    below: 50
    for: "00:05:00"
  action:
  - alias: "vapauta muistia"
    service: hassio.addon_restart
    data:
      addon: a0d7b954_appdaemon