- id: fireplace_fan_on
  alias: Puhallus päälle kun takka on päällä
  trigger:
  - platform: numeric_state
    entity_id: sensor.takka_temperature
    above: 40
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.pumppu
      hvac_mode: fan_only
  - service: climate.set_fan_mode
    data:
      entity_id: climate.pumppu
      fan_mode: LowMid
- id: fireplace_fan_off
  alias: Puhallus pois kun takka on kylmä
  trigger:
  - platform: numeric_state
    entity_id: sensor.takka_temperature
    below: 35
    for:
      minutes: 2
  condition:
  - condition: state
    entity_id: climate.pumppu
    state: fan_only
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.pumppu
      hvac_mode: "{% if (is_state('input_select.heatingmode','Jäähdytys')) %}cool{% else %}heat{% endif %}"
  - service: climate.set_fan_mode
    data:
      entity_id: climate.pumppu
      fan_mode: Auto
  - service: climate.set_temperature
    data_template:
      entity_id: climate.pumppu
      temperature: "{{states('input_number.temperature') |float}}"
- id: heatpump_to_cooling_evening
  alias: Pumppu viilennykselle illalla
  trigger:
  - platform: time
    at: '23:30'
  condition:
  - condition: template
    value_template:  "{{ states('sensor.2_olohuone') |float > states('input_number.temperature') |float +1 }}"
  action:
  - service: climate.turn_on
    entity_id: climate.pumppu
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.pumppu
      hvac_mode: cool
  - service: climate.set_temperature
    data_template:
      entity_id: climate.pumppu
      temperature: "{{states('input_number.temperature') |float -1}}"
- id: heatpump_off
  alias: Pumppu pois
  trigger:
  - platform: time
    at: '05:00'
  action:
  - service: climate.turn_off
    entity_id: climate.pumppu
- id: heatpump_on
  alias: Pumppu päälle
  trigger:
  - platform: time
    at: '6:55'
  - platform: state
    entity_id: input_number.temperature
  - platform: state
    entity_id: input_select.heatingmode
  action:
  - service: climate.turn_on
    entity_id: climate.pumppu
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.pumppu
      hvac_mode: "{% if (is_state('input_select.heatingmode','Jäähdytys')) %}cool{% else %}heat{% endif %}"
  - service: climate.set_temperature
    data_template:
      entity_id: climate.pumppu
      temperature: "{{states('input_number.temperature') |float}}"
- id: Shower_used
  alias: Suihkussa käyty
  trigger:
  - platform: numeric_state
    entity_id: sensor.humidity_5
    above: 75
  condition:
  - condition: state
    entity_id: timer.shower
    state: "idle"    
  action:
  - service: input_select.select_option
    target:
      entity_id: input_select.showerheating
    data:
      option: Termostaatti
  - service: timer.start
    data:
      duration: "{{ states('input_datetime.shower_duration')}}"
    target:
      entity_id: timer.shower
- id: Shower_heated
  alias: Suihku lämmitetty
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.shower
  action:
  - service: input_select.select_option
    target:
      entity_id: input_select.showerheating
    data:
      option: Esto
  - service: input_datetime.set_datetime
    target:
      entity_id: input_datetime.shower_duration
    data:
      time: "03:55:00"
- id: Sauna_heated
  alias: Sauna lämmitetty
  trigger:
  - platform: numeric_state
    entity_id: sensor.sauna_temperature
    above: 35
  action:
  - service: input_datetime.set_datetime
    target:
      entity_id: input_datetime.shower_duration
    data:
      time: "01:55:00"
# - id: No_heating
#   alias: Pohjalaattaa ei lämmitetty
#   trigger:
#   - platform: numeric_state
#     entity_id: sensor.takka_temperature
#     below: 30
#     for: "24:00:00"
#   action:
#   - service: input_boolean.turn_on
#     target:
#       entity_id: input_boolean.heating
- alias: Force_house_heating
  trigger:
  - platform: time
    at: "03:00:00"
  action:
  - service: input_select.select_option
    data:
      option: Pakko
    target:
      entity_id: input_select.housestatus
- alias: Force_house_heating_off
  trigger:
  - platform: time
    at: "04:00:00"
  action:
  - service: input_select.select_option
    data:
      option: Esto
    target:
      entity_id: input_select.housestatus
- id: Fireplace_cold
  alias: Takka kylmä
  trigger:
  - platform: numeric_state
    entity_id: sensor.takka_temperature
    below: 9
    for: "00:10:00"
  - platform: numeric_state
    entity_id: sensor.2_olohuone
    below: 18
    for: "00:10:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.housestatus
        state: "Pitkään poissa"
  action:
  - service: input_select.select_option
    target:
      entity_id: input_select.househeating
    data:
      option: Termostaatti
- id: House warm
  alias: Talo lämmin
  trigger:
  - platform: numeric_state
    entity_id: sensor.takka_temperature
    above: 20
    for: "00:20:00"
  - platform: numeric_state
    entity_id: sensor.2_olohuone
    above: 21
    for: "00:10:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.housestatus
        state: "Pitkään poissa"
      - condition: numeric_state
        entity_id: sensor.2_olohuone
        above: 20
  action:
  - service: input_select.select_option
    target:
      entity_id: input_select.househeating
    data:
      option: Esto
- id: sauna_cold
  alias: Sauna kylmä
  trigger:
  - platform: numeric_state
    entity_id: sensor.sauna_temperature
    below: 17
    for: "00:10:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.housestatus
        state: "Pitkään poissa"
  action:
  - service: input_select.select_option
    target:
      entity_id: input_select.showerheating
    data:
      option: Termostaatti
- id: sauna_not_cold
  alias: Sauna lämmitys pois
  trigger:
  - platform: numeric_state
    entity_id: sensor.sauna_temperature
    above: 18
    for: "00:10:00"
  condition:
    - condition: and
      conditions:
      - condition: state
        entity_id: input_select.housestatus
        state: "Pitkään poissa"
  action:
  - service: input_select.select_option
    target:
      entity_id: input_select.showerheating
    data:
      option: Esto
- id: shower_heating_block
  alias: Suihkun lämmityksen esto
  trigger:
  - platform: state
    entity_id: input_select.showerheating
    to: Esto
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.suihku_esto
  - service: switch.turn_off
    data:
      entity_id: switch.suihku_termostaatti
- id: shower_heating_thermostat
  alias: Suihkun lämmitys termostaatti
  trigger:
  - platform: state
    entity_id: input_select.showerheating
    to: Termostaatti
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.suihku_termostaatti
  - service: switch.turn_off
    data:
      entity_id: switch.suihku_esto
- id: shower_heating_force
  alias: Suihkun lämmitys pakko
  trigger:
  - platform: state
    entity_id: input_select.showerheating
    to: Pakko
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.suihku_termostaatti
  - service: switch.turn_off
    data:
      entity_id: switch.suihku_esto
- id: house_heating_block
  alias: Talon lämmityksen esto
  trigger:
  - platform: state
    entity_id: input_select.househeating
    to: Esto
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.talo_esto
  - service: switch.turn_off
    data:
      entity_id: switch.talo_termostaatti
- id: house_heating_thermostat
  alias: Talon lämmitys termostaatti
  trigger:
  - platform: state
    entity_id: input_select.househeating
    to: Termostaatti
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.talo_termostaatti
  - service: switch.turn_off
    data:
      entity_id: switch.talo_esto
- id: house_heating_force
  alias: Talo lämmitys pakko
  trigger:
  - platform: state
    entity_id: input_select.househeating
    to: Pakko
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.talo_termostaatti
  - service: switch.turn_off
    data:
      entity_id: switch.talo_esto
- id: ventilation_inflow_temp
  alias: Ilmanvaihto tulo ohjaukselle
  trigger:
  - platform: state
    entity_id: input_select.ventilation
    to: Tuloilma
  - platform: state
    entity_id: input_number.temperature
  - platform: state
    entity_id: input_select.heatingmode
    to: Lämmitys
  condition:
  - condition: state
    entity_id: input_select.heatingmode
    state: Lämmitys
  - condition: state
    entity_id: input_select.ventilation
    state: Tuloilma
  action:
  - service: modbus.write_register
    data:
      value: 1
      hub: enervent
      slave: 1
      address: 136
  - service: modbus.write_register
    data:
      value: "{{(states('input_number.temperature') |int -2)*10}}"
      hub: enervent
      slave: 1
      address: 135
  - service: modbus.write_coil
    data:
      state: 1
      hub: enervent
      slave: 1
      address: 54
- id: ventilation_outflow_temp
  alias: Ilmanvaihto poisto ohjaukselle
  trigger:
  - platform: state
    entity_id: input_select.ventilation
    to: Poistoilma
  - platform: state
    entity_id: input_select.heatingmode
  - platform: state
    entity_id: input_number.temperature
  condition:
  - condition: state
    entity_id: input_select.ventilation
    state: "Poistoilma"
  action:
  - service: modbus.write_register
    data:
      value: 2
      hub: enervent
      slave: 1
      address: 136
  - service: modbus.write_register
    data:
      value: "{% if (is_state('input_select.heatingmode','Jäähdytys')) %}{{(states('input_number.temperature') |int -2)*10}}{% else %}{{(states('input_number.temperature') |int +2)*10}}{% endif %}"
      hub: enervent
      slave: 1
      address: 135
  - service: modbus.write_coil
    data:
      state: 0
      hub: enervent
      slave: 1
      address: 54
- id: ventilation_to_inflow_temp
  alias: Ilmanvaihto lämmitykselle
  trigger:
  - platform: numeric_state
    entity_id: sensor.air_ventilation_hrc_supply_air_temperature
    below: 12
    for: "00:10:00"
  action:
  - service: input_select.select_option
    data:
      option: Tuloilma
    target:
      entity_id: input_select.ventilation
- id: ventilation_to_outflow_temp
  alias: Ilmanvaihto lämmitys pois
  trigger:
  - platform: numeric_state
    entity_id: sensor.air_ventilation_hrc_supply_air_temperature
    above: 13
    for: "00:10:00"
  action:
  - service: input_select.select_option
    data:
      option: Poistoilma
    target:
      entity_id: input_select.ventilation