- id: fireplace_fan_on
  alias: Puhallus päälle kun takka on päällä
  trigger:
  - platform: numeric_state
    entity_id: sensor.takka_temperature
    above: 40
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.pumppu
      hvac_mode: fan_only
  - service: climate.set_fan_mode
    data:
      entity_id: climate.pumppu
      fan_mode: LowMid
- id: fireplace_fan_off
  alias: Puhallus pois kun takka on kylmä
  trigger:
  - platform: numeric_state
    entity_id: sensor.takka_temperature
    below: 35
    for:
      minutes: 2
  condition:
  - condition: state
    entity_id: climate.pumppu
    state: fan_only
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.pumppu
      hvac_mode: heat
  - service: climate.set_fan_mode
    data:
      entity_id: climate.pumppu
      fan_mode: Auto
  - service: climate.set_temperature
    data_template:
      entity_id: climate.pumppu
      temperature: "{{states('input_number.temperature') |float}}"
- id: heatpump_to_cooling_evening
  alias: Pumppu viilennykselle illalla
  trigger:
  - platform: time
    at: '23:30'
  condition:
  - condition: template
    value_template:  "{{ states('sensor.temperature_4') |float > states('input_number.temperature') |float +2 }}"
  action:
  - service: climate.turn_on
    entity_id: climate.pumppu
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.pumppu
      hvac_mode: cool
  - service: climate.set_temperature
    data_template:
      entity_id: climate.pumppu
      temperature: "{{states('input_number.temperature') |float -2}}"
- id: heatpump_off_morning
  alias: Pumppu  pois aamulla
  trigger:
  - platform: time
    at: '05:50'
  action:
  - service: climate.turn_off
    entity_id: climate.pumppu
- id: heatpump_off_evening
  alias: Pumppu  pois illalla
  trigger:
  - platform: time
    at: '23:30'
  action:
  - service: climate.turn_off
    entity_id: climate.pumppu
- id: heatpump_to_heating_morning
  alias: Pumppu lämmitykselle aamulla
  trigger:
  - platform: time
    at: '8:30'
  action:
  - service: climate.turn_on
    entity_id: climate.pumppu
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.pumppu
      hvac_mode: heat
  - service: climate.set_temperature
    data_template:
      entity_id: climate.pumppu
      temperature: "{{states('input_number.temperature') |float}}"
- id: Shower_used
  alias: Suihkussa käyty
  trigger:
  - platform: numeric_state
    entity_id: sensor.humidity_5
    above: 75
  action:
  - service: input_select.select_option
    target:
      entity_id: input_select.showerheating
    data:
      option: Termostaatti
  - service: timer.start
    target:
      entity_id: timer.shower
- id: Shower_heated
  alias: Suihku lämmitetty
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.shower
  action:
  - service: input_select.select_option
    target:
      entity_id: input_select.showerheating
    data:
      option: Esto
  - service: input_datetime.set_datetime
    target:
      entity_id: input_datetime.shower_duration
    data:
      time: "03:55:00"
- id: Sauna_heated
  alias: Sauna lämmitetty
  trigger:
  - platform: numeric_state
    entity_id: sensor.sauna_temperature
    above: 35
  action:
  - service: input_datetime.set_datetime
    target:
      entity_id: input_datetime.shower_duration
    data:
      time: "01:55:00"
- id: No_heating
  alias: Pohjalaattaa ei lämmitetty
  trigger:
  - platform: numeric_state
    entity_id: sensor.takka_temperature
    below: 30
    for: "24:00:00"
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.heating
- id: shower_heating_block
  alias: Suihkun lämmityksen esto
  trigger:
  - platform: state
    entity_id: input_select.showerheating
    to: Esto
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.suihku_esto
  - service: switch.turn_off
    data:
      entity_id: switch.suihku_termostaatti
- id: shower_heating_thermostat
  alias: Suihkun lämmitys termostaatti
  trigger:
  - platform: state
    entity_id: input_select.showerheating
    to: Termostaatti
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.suihku_termostaatti
  - service: switch.turn_off
    data:
      entity_id: switch.suihku_esto
- id: shower_heating_force
  alias: Suihkun lämmitys pakko
  trigger:
  - platform: state
    entity_id: input_select.showerheating
    to: Pakko
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.suihku_termostaatti
  - service: switch.turn_off
    data:
      entity_id: switch.suihku_esto
- id: house_heating_block
  alias: Talon lämmityksen esto
  trigger:
  - platform: state
    entity_id: input_select.househeating
    to: Esto
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.talo_esto
  - service: switch.turn_off
    data:
      entity_id: switch.talo_termostaatti
- id: house_heating_thermostat
  alias: Talon lämmitys termostaatti
  trigger:
  - platform: state
    entity_id: input_select.househeating
    to: Termostaatti
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.talo_termostaatti
  - service: switch.turn_off
    data:
      entity_id: switch.talo_esto
- id: house_heating_force
  alias: Talo lämmitys pakko
  trigger:
  - platform: state
    entity_id: input_select.househeating
    to: Pakko
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.talo_termostaatti
  - service: switch.turn_off
    data:
      entity_id: switch.talo_esto