- id: decoration_lights_on
  alias: Valot päälle ennen aurinkolaskua
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: 0
  - platform: numeric_state
    entity_id: sensor.spot_cost
    below: 40
  - platform: template
    value_template: >
      {{ is_state('sensor.time', '08:00' if is_state('binary_sensor.workday_sensor', 'off') else '07:00') }}
  condition:
  - condition: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: 0.1  
  - condition: numeric_state
    entity_id: sensor.spot_cost
    below: 40
  - condition: time
    after: "07:00:00"
    before: "23:00:00"
  action:
  - service: switch.turn_on
    entity_id: group.koristevalot
- id: decoration_lights_outside_on
  alias: Ulkovalot päälle ennen aurinkolaskua
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: 0
  condition:
  - condition: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: 0.1
  - condition: time
    after: "14:00:00"
    before: "21:00:00"
  - condition: numeric_state
    entity_id: sensor.spot_cost
    below: 20
  action:
  - service: switch.turn_on
    entity_id: switch.ajopiha
- id: decoration_lights_outside_off
  alias: Valot pois klo 21 ja aamulla kun aurinko on noussut
  trigger:
  - platform: time
    at: '21:10'
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    above: -0.9
  - platform: numeric_state
    entity_id: sensor.spot_cost
    above: 20
  action:
  - service: switch.turn_off
    entity_id: group.pihavalot
- id: decoration_lights_off
  alias: Valot pois klo 23 ja aamulla kun aurinko on noussut
  trigger:
  - platform: time
    at: '23:10'
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    above: -0.9
  - platform: numeric_state
    entity_id: sensor.spot_cost
    above: 40
  action:
  - service: switch.turn_off
    entity_id: group.koristevalot
  - service: switch.turn_off
    entity_id: group.pihavalot
- id: decoration_lights_off_Joonas
  alias: Valot pois klo 19:30
  trigger:
  - platform: time
    at: '19:30'
  action:
  - service: switch.turn_off
    entity_id: switch.p5
- id: Flora_lights_on
  alias: Kukkavalot päälle 
  trigger:
  - platform: state
    entity_id: input_boolean.flora
    from: 'off'
    to: 'on'
  action:
  - service: switch.turn_on
    entity_id: group.kukkavalot
  - service: switch.turn_on
    entity_id: group.kukkavalot_late
  - service: light.turn_on
    entity_id: light.kukkavalot
- id: Flora_lights_off
  alias: Kukkavalot pois 
  trigger:
  - platform: state
    entity_id: input_boolean.flora
    from: 'on'
    to: 'off'
  action:
  - service: switch.turn_off
    entity_id: group.kukkavalot
  - service: switch.turn_off
    entity_id: group.kukkavalot_late
  - service: light.turn_off
    entity_id: light.kukkavalot
- id: Evening_scene_on
  alias: Olohuoneen valot himmeälle illala
  trigger:
  - platform: state
    entity_id: media_player.samsung_ue55ku6075
    to: 'on'
  condition:
  - condition: time
    after: '20:00:00'
    before: '23:00:00'
  action:
  - service: scene.turn_on
    entity_id: scene.evening
  - service: media_player.volume_set
    data:
      entity_id: media_player.samsung_tv_remote
      volume_level: 0
- id: Bathroom_light
  alias: Vessan valot
  trigger:
    platform: state
    entity_id: binary_sensor.presence_9
    to: 'on'
  condition:
  - condition: time
    after: '22:00:01'
    before: '06:00:00'
  action:
  - service: light.turn_on
    data:
      entity_id: light.koristevalo
      brightness: 1
- id: Bathroom_light_off
  alias: Vessan valot pois
  trigger:
    platform: state
    entity_id: binary_sensor.presence_9
    to: 'off'
    for:
      minutes: 5
  action:
  - service: light.turn_off
    entity_id: light.koristevalo
- id: Bathroom_lights
  alias: Ison vessan peilivalo
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/KytkinIsoWC2/action"
    payload: single
  action:
  - service: switch.toggle
    entity_id: switch.peilikaappi
# - id: Bathroom_lights_night
#   alias: Ison vessan valot yöllä
#   trigger:
#     platform: event
#     event_type: deconz_event
#     event_data:
#       id: isowc
#       event: 1002
#   condition:
#   - condition: time
#     after: '21:00:01'
#     before: '05:59:59'
#   action:
#   - service: light.toggle
#     data:
#       entity_id: light.Isowc1
#       brightness: 1
- id: hallway_lights_on
  alias: Käytävän valot päälle
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/KytkinEteinen/action"
    payload: brightness_up_click
  - platform: mqtt
    topic: "zigbee2mqtt/KytkinRuokahuone/action"
    payload: brightness_up_click
  - platform: mqtt
    topic: "zigbee2mqtt/KytkinKeittio/action"
    payload: brightness_up_click
  action:
  - service: light.turn_on
    entity_id: light.kaytava_yla
  - service: light.turn_on
    entity_id: light.kaytava_ala    
- id: hallway_lights_off
  alias: Käytävän valot pois
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/KytkinEteinen/action"
    payload: brightness_down_click
  - platform: mqtt
    topic: "zigbee2mqtt/KytkinRuokahuone/action"
    payload: brightness_down_click
  - platform: mqtt
    topic: "zigbee2mqtt/KytkinKeittio/action"
    payload: brightness_down_click
  action:
  - service: light.turn_off
    entity_id: light.kaytava_yla
  - service: light.turn_off
    entity_id: light.kaytava_ala    
- id: all_lights_off_timer
  alias: Valot pois ajastin
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/KytkinEteinen/action"
    payload: toggle
  action:
  - service: timer.start
    data:
      entity_id: timer.all_lights_off
      duration: '0:05:00'
- id: All_lights_off
  alias: Kaikki valot pois
  trigger:
    platform: state
    entity_id: binary_sensor.etuovianturi_contact
    to: 'on'
  condition:
  - condition: state
    entity_id: timer.all_lights_off
    state: active
  action:
  - service: switch.turn_off
    entity_id: group.koristevalot
  - service: switch.turn_off
    entity_id: group.vanhat_valot
  - service: light.turn_off
    entity_id: light.kaikki_valot
- id: storage_lights
  alias: Vaatehuoneen valot
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/KytkinKodinhoitohuone2/action"
    payload: arrow_right_click
  - platform: mqtt
    topic: "zigbee2mqtt/KytkinKodinhoitohuone2/action"
    payload: arrow_left_click
  - platform: mqtt
    topic: "zigbee2mqtt/KytkinKodinhoitohuone2/action"
    payload: brightness_up_click
  - platform: mqtt
    topic: "zigbee2mqtt/KytkinKodinhoitohuone2/action"
    payload: brightness_down_click
  - platform: mqtt
    topic: "zigbee2mqtt/KytkinVaatehuone/action"
    payload: arrow_right_click
  - platform: mqtt
    topic: "zigbee2mqtt/KytkinVaatehuone/action"
    payload: arrow_left_click
  - platform: mqtt
    topic: "zigbee2mqtt/KytkinVaatehuone/action"
    payload: brightness_up_click
  - platform: mqtt
    topic: "zigbee2mqtt/KytkinVaatehuone/action"
    payload: brightness_down_click
  - platform: mqtt
    topic: "zigbee2mqtt/KytkinVaatehuone/action"
    payload: toggle
  action:
  - service: switch.toggle
    entity_id: switch.vaatehuone
- id: laundryroom_lights
  alias: Kodinhoitohuoneen valot
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/KytkinKodinhoitohuone/action"
    payload: toggle
  - platform: mqtt
    topic: "zigbee2mqtt/KytkinKodinhoitohuone2/action"
    payload: toggle
  action:
  - service: switch.toggle
    entity_id: switch.kodinhoitohuone
- id: diningroom_lights
  alias: Ruokahuone valot
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/KytkinRuokahuone/action"
    payload: toggle
  - platform: mqtt
    topic: "zigbee2mqtt/KytkinKeittio/action"
    payload: toggle
  - platform: mqtt
    topic: "zigbee2mqtt/KytkinKeittio/action"
    payload: arrow_left_click
  action:
  - service: switch.toggle
    entity_id: switch.ruokahuone
- id: sauna_lights
  alias: Sauna valot
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/KytkinSauna/action"
    payload: toggle
  action:
  - service: switch.toggle
    entity_id: switch.sauna
- id: Joonas_lights_on
  alias: Joonaksen valot päälle
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/Kytkin_Joonas/action"
    payload: on
  action:
  - service: switch.turn_on
    entity_id: switch.p7
- id: Joonas_lights_off
  alias: Joonaksen valot pois
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/Kytkin_Joonas/action"
    payload: off
  action:
  - service: switch.turn_on
    entity_id: switch.p7
- id: kitchen_lights
  alias: Keittiö valot
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/KytkinKeittio/action"
    payload: arrow_right_click
  - platform: mqtt
    topic: "zigbee2mqtt/KytkinRuokahuone/action"
    payload: arrow_right_click
  action:
  - service: switch.toggle
    entity_id: switch.keittio_2
- id: Notification
  alias: Ilmoitus liikkeestä
  trigger:
    platform: state
    entity_id: binary_sensor.presence_19
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: time
      after: '7:00:01'
      before: '19:45:00'
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state:  
        - armed_away
        - armed_home
  action:
  - service: notify.mobile_app_huaweip9
    data:
      message: TTS
      title: Hälytys Joonakselle liikettä havaittu leikkihuoneessa. Tule heti paikalle.
      data:
        channel: alarm_stream
- id: Smartlock
  alias: Älylukko auki
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: smartlock
      event: 1002
  action:
  - alias: "Avaa etuovi"
    service: lock.unlock
    target:
      entity_id: lock.etuovi
    data:
      code: !secret lock_code
- id: Smartlock_lock
  alias: Älylukko lukkoon
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: smartlock
      event: 2002
  action:
  - alias: "Lukitse etuovi"
    service: lock.lock
    target:
      entity_id: lock.etuovi
- id: Sauna_lights_auto_off
  alias: Saunanvalot pois 
  trigger:
  - platform: state
    entity_id: switch.sauna
    from: "off"
    to: "on"
    for: "04:00:00"
  action:
  - service: switch.turn_off
    entity_id: switch.sauna
- id: Closet_lights_auto_off
  alias: Vaatehuone valot pois 
  trigger:
  - platform: state
    entity_id: switch.vaatehuone
    from: "off"
    to: "on"
    for: "02:00:00"
  action:
  - service: switch.turn_off
    entity_id: switch.vaatehuone
- id: Utility_lights_auto_off
  alias: Kodinhoitohuone valot pois 
  trigger:
  - platform: state
    entity_id: switch.kodinhoitohuone
    from: "off"
    to: "on"
    for: "02:00:00"
  action:
  - service: switch.turn_off
    entity_id: switch.kodinhoitohuone