  - platform: template
    sensors:
      golf_0b:
        value_template: "{{ is_state('sensor.golf_0',states('sensor.time')|string) }}"
      golf_10b:
        value_template: "{{ is_state('sensor.golf_10',states('sensor.time')|string) }}"
      golf_20b:
        value_template: "{{ is_state('sensor.golf_20',states('sensor.time')|string) }}"
      octavia_0b:
        value_template: "{{ is_state('sensor.octavia_0',states('sensor.time')|string) }}"
      octavia_10b:
        value_template: "{{ is_state('sensor.octavia_10',states('sensor.time')|string) }}"
      octavia_20b:
        value_template: "{{ is_state('sensor.octavia_20',states('sensor.time')|string) }}"
      palju:
        value_template: "{{ states('sensor.ulko_temperature')|float>8 }}"
      sisaheatneeded:
        value_template: "{{ states('sensor.2_olohuone') |float < states('input_number.temperature') |float }}"
  - platform: workday
    country: FI