homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  allowlist_external_dirs:
  - /tmp
  latitude: !secret lat
  longitude: !secret lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 32
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Helsinki
  # Customization file
  customize_glob:
    "sensor.golf_*":
      hidden: true
    "binary_sensor.golf_*":
      hidden: true
    "sensor.octavia_*":
      hidden: true
    "binary_sensor.octavia_*":
      hidden: true
    "input_boolean.octavia_*":
      hidden: true
    "input_boolean.golf_*":
      hidden: true  
  auth_mfa_modules:
    - type: totp
      name: Authenticator app

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
recorder:
  db_url: !secret dburl
  exclude:
    entities:
      - sun.sun
      - sensor.time

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# google_assistant:
  # project_id: homeassistantsync-259019
  # service_account: !include HomeAssistantSync.json
  # secure_devices_pin: !secret pin
  # report_state: true
  # exposed_domains:
    # - switch
    # - light
    # - cover
  # entity_config:
    # switch.kitchen:
      # name: CUSTOM_NAME_FOR_GOOGLE_ASSISTANT
      # aliases:
        # - BRIGHT_LIGHTS
        # - ENTRY_LIGHTS
    # light.living_room:
      # expose: false
      # room: LIVING_ROOM
# Discover some devices automatically
discovery:

scene:
  - name: Evening
    entities:
      light.olohuone_iso : off
      light.olohuone_ovet: off
      light.olohuone_pieni:
        state: on
        brightness: 40
        color_temp: 420
    
# Sensors
sensor: !include sensors.yaml
binary_sensor: !include binarysensors.yaml

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_chat1
      - !secret telegram_chat2
      - !secret telegram_chat3
notify:
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_chat1
  
cover:
  - platform: mqtt
    name: "Autotallin ovi"
    state_topic: "garage/door/1/status"
    command_topic: "garage/door/1/action"
    availability_topic: "GarHAge/availability"
    qos: 0
    optimistic: false
    retain: false
    payload_open: "OPEN"
    payload_close: "CLOSE"
    payload_stop: "STATE"
    state_open: "open"
    state_closed: "closed"
    payload_available: "online"
    payload_not_available: "offline"
    device_class: garage
light:
  - platform: group
    name: Olohuone kaikki valot
    entities:
    - light.olohuone_iso
    - light.olohuone_pieni
    - light.olohuone_ovet
  - platform: group
    name: Tyohuone kaikki valot
    entities:
    - light.tyohuone
    - light.tyohuone_lednauha
    - light.tyohuone_ledpaneelit
  - platform: group
    name: Kaikki valot
    entities:
    - light.tyohuone_lednauha
    - light.tyohuone_ledpaneelit
    - light.tyohuone
    - light.olohuone_iso
    - light.olohuone_pieni
    - light.olohuone_ovet
    - light.wc
    - light.makuuhuone
    - light.koristevalo
    - light.leikkihuone
    - light.vierashuone
    - light.suihku
    
input_boolean:
  golf:
    name: Golf automaatti
    icon: mdi:car
  golf_s:
  octavia:
    name: Octavia automaatti
    icon: mdi:car
  octavia_s:
  pumppu:
    name: Uima-allas pumppu
  awaymode:
    name: Pitkään poissa
  flora:
    name: Kasvivalot
input_datetime:
  golf:
    name: Golf lämmitys aika
    has_date: false
    has_time: true
  octavia:
    name: Octavia lämmitys aika
    has_date: false
    has_time: true
input_number:
  temperature:
    name: Lämpötila
    initial: 22
    min: 19
    max: 25
    step: 0.5
    icon: mdi:temperature-celsius+
input_select:
  housestatus:
    name: Talon tila
    options: 
      - Päivä
      - Yö
      - Hetken poissa
      - Pitkään poissa
    initial: Päivä
    icon: mdi:home
    
# modbus:
  # name: enervent
  # type: serial
  # method: rtu
  # port: /dev/ttyUSB0
  # baudrate: 19200
  # stopbits: 1
  # bytesize: 8
  # parity: N
  # timeout: 1
  
alarm_control_panel:
  - platform: manual
    code: '3180'
timer:
  octavia:
    name: Octavia lämmitys jäljellä
  golf:
    name: Golf lämmitys jäljellä
  garagedooropen:
    name: Autotallin oven avaus
  garagedoorclose:
    name: Autotallin oven sulkeminen
  all_lights_off:
    name: kaikki valot pois
# Text to speech
tts:
  - platform: google_translate
media_player:
  - platform: samsungtv_tizen
    host: !secret tv_host
    port: 8002
    mac: 40:16:3b:0f:c9:95
group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml