koristevalot:
  name: Koristevalot
  entities:
    - switch.p7
    - switch.olohuone1
    - switch.olohuone2
    - switch.keittio
    - switch.tyohuone
    - switch.p9
    - switch.p13
    - switch.p2
kukkavalot:
  name: Kukkavalot
  entities:
    - switch.p15
    - switch.p1
    - switch.wc_kukkavalo
    - switch.p14
    - switch.p8
kukkavalot_late:
  name: kukkavalot myöhemmin
    - switch.p12
    - switch.p11
autotallinovet:
  name: Autotallin ovet
  entities:
     - binary_sensor.puutarhavarasto
     - binary_sensor.sivuovi
     - binary_sensor.kylmavarasto
     - binary_sensor.autotallin_ovi
vanhat_valot:
  name: Vanhat valot
  entities:
    - switch.vaatehuone #Eteinen
    - switch.kaytava
    - switch.peilikaappi #Peilivalo
    - switch.kodinhoitohuone    # Kodinhoitohuone
    - switch.sauna
    - switch.ruokahuone
    - switch.keittio_2