koristevalot:
  name: Koristevalot
  entities:
    - switch.p7
    - switch.p4
    - switch.olohuone2
    - switch.keittio
    - switch.p9
    - switch.p13
    - switch.p2
    - switch.p17

    - switch.p6
    - switch.p19
pihavalot:
 name: Pihavalot
 entities:
    - switch.takapiha
kukkavalot:
  name: Kukkavalot
  entities:
    - switch.p15
    - switch.p1
    - switch.wc_kukkavalo
    - switch.p14
    - switch.p8
    - switch.p16
    - switch.p18
    - switch.p12
    - switch.tkukkavalot
kukkavalot_late:
  name: kukkavalot myöhemmin
  entities:
    - switch.p11
autotallinovet:
  name: Autotallin ovet
  entities:
     - binary_sensor.puutarhavarasto
     - binary_sensor.sivuovi
     - binary_sensor.kylmavarasto
     - binary_sensor.autotallin_ovi
vanhat_valot:
  name: Vanhat valot
  entities:
    - switch.vaatehuone
    - switch.peilikaappi #Peilivalo
    - switch.kodinhoitohuone    # Kodinhoitohuone
    - switch.sauna
    - switch.ruokahuone
    - switch.keittio_2