koristevalot:
  name: Koristevalot
  entities:
    - switch.p4
    - switch.olohuone2
    - switch.p3
    - switch.p9
    - switch.p13
    - switch.p2
    - switch.p6
    - switch.p16
    - switch.p10
    - swiich.p5
    - switch.p18
pihavalot:
 name: Pihavalot
 entities:
    - switch.takapiha
    - switch.etupiha
    - switch.ajopiha
kukkavalot:
  name: Kukkavalot
  entities:
    - switch.p15
    - switch.p1
    - switch.wc_kukkavalo
    - switch.p14
    - switch.p8
    - switch.p12
    - switch.tkukkavalot
    - switch.p11
    - switch.p19
    - switch.p17
# kukkavalot_late:
#   name: kukkavalot myöhemmin
#   entities:
   
autotallinovet:
  name: Autotallin ovet
  entities:
     - binary_sensor.puutarhavarasto
     - binary_sensor.sivuovi
     - binary_sensor.kylmavarasto
     - binary_sensor.autotallin_ovi
vanhat_valot:
  name: Vanhat valot
  entities:
    - switch.vaatehuone
    - switch.peilikaappi #Peilivalo
    - switch.kodinhoitohuone    # Kodinhoitohuone
    - switch.sauna
    - switch.ruokahuone
    - switch.keittio_2